Algoritmo "o "PARA" exemplo de laco de repeticao"
// Disciplina   : [Lógica de Programação]
// Professor   :obama
// Descrição   : Aqui esta um exemplo do laco de repeticao "para"
// Autor(a)    : Paulo Rossetto
// Data atual  : 17/09/2024
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 10 passo 1 faca
      escreval("Jailson")
   fimpara

Fimalgoritmo